# lab 1

# language: cpp
# before_script:
# - sudo apt-get install libboost-test-dev -y
# - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
# - sudo apt-get update -qq
# # - git clone https://github.com/google/googletest.git
# script:
# - cd lab1-hello_world
# - cmake .
# - cmake --build .
# - cmake --build . --target test
# - cmake --build . --target package
# deploy:
#   provider: script
#   skip_cleanup: true
#   script:
#   - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uustinsky:$BINTRAY_API_KEY "https://api.bintray.com/content/ustinsky/otus-cpp/helloworld/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

# lab 2

# language: cpp
# before_script:
# - sudo apt-get install libboost-test-dev -y
# - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
# - sudo apt-get update -qq

# script:
# - cd lab2-ip_filter
# - cmake .
# - cmake --build .
# - cmake --build . --target test
# - cmake --build . --target package

# deploy:
#   provider: script
#   skip_cleanup: true
#   script:
#   - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uustinsky:$BINTRAY_API_KEY "https://api.bintray.com/content/ustinsky/otus-cpp/ip_filter/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

# lab 3
# dist: bionic
# language: cpp
# before_script:

# # - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
# - sudo apt-get update -qq
# - sudo apt-get install -qq g++-7 libboost-test-dev
# # - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
# script:
# - cd lab3-allocator/
# - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7
# - cmake .
# - cmake --build .
# - cmake --build . --target test
# - cmake --build . --target package
# deploy:
#   provider: script
#   skip_cleanup: true
#   script:
#   - curl -T allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uustinsky:$BINTRAY_API_KEY "https://api.bintray.com/content/ustinsky/otus-cpp/allocator/$TRAVIS_BUILD_NUMBER/allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

# lab 4
dist: bionic
language: cpp
before_script:
- sudo apt-get update -qq
- sudo apt-get install -qq g++ libgtest-dev doxygen -y 
- export m_pwd=$(pwd)
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- sudo mkdir -p /usr/local/lib/gtest/
- sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
- sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a
- cd ${m_pwd}



script:
- cd lab4-print_ip/
# - git clone --recursive https://github.com/google/googletest.git
# - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uustinsky:$BINTRAY_API_KEY "https://api.bintray.com/content/ustinsky/otus-cpp/allocator/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
